openapi: '3.0.3'
info:
  title: 'Example - Control API'
  version: '1.0'
  description: |-
    Example - Control API

    We use the API Specification to describe each endpoint. The API self-description also contains type information to help you error-check your requests.

    # Authentication

    Bearer token - Auth is provided by bearer token. Tokens are managed on platform interface. 

    <!-- ReDoc-Inject: <security-definitions> -->
  contact:
    name: Developers Contact
    email: developers@example.com
  license:
    name: 'private-license'
    url: 'https://example.com/cgu'

servers:
  - url: 'https://example-test.com/v1/control'
    description: API base url.

paths:
  '/healthcheck':
    $ref: endpoints/healthcheck/healthcheck.yaml

  # API
  '/apis':
    $ref: endpoints/v1/apis/apis.yaml
  '/apis/{api_id}':
    $ref: endpoints/v1/apis/apis@id.yaml

  # OAS
  '/apis/{api_id}/oas':
    $ref: endpoints/v1/oas/apis@id@oas.yaml
  '/apis/{api_id}/oas/_upload':
    $ref: endpoints/v1/oas/apis@id@oas@_upload.yaml
  '/apis/{api_id}/oas/{oas_id}/_download':
    $ref: endpoints/v1/oas/apis@id@oas@id@_download.yaml
  '/apis/{api_id}/oas/{oas_id}':
    $ref: endpoints/v1/oas/apis@id@oas@id.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
