openapi: 3.0.3
info:
  x-logo:
    url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrknBmeAljcWMcxd4dqRro5K0sur9-7qY6Fg&usqp=CAU
  title: API PetStore
  description: |-
    API PetStore

    # Authentication

    Token JWT - Authentication needs a provided token

    <!-- ReDoc-Inject: <security-definitions> -->
  termsOfService: https://example-api.com/
  contact:
    name: John Doe
    email: john.doe@gmail.com
    url: https://example-api.com/
  version: 0.1.0
  license:
    name: 'John Doe'
    url: https://example-api.com/
servers:
  - url: 'https://api-{env}.example-api.com/v1/petstore'
    description: ci/staging APIs URL.
    variables:
      env:
        description: environment
        default: staging
        enum:
          - ci
          - staging

paths:
  '/healthcheck':
    $ref: ./endpoint/healthcheck/healthcheck.yaml
    
  '/pet':
    $ref: ./endpoint/pet/pet.yaml
  '/pet/{id}':
    $ref: ./endpoint/pet/pet@id.yaml

  '/category':
    $ref: ./endpoint/category/category.yaml
  '/category/{id}':
    $ref: ./endpoint/category/category@id.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

externalDocs:
  description: Documentation
  url: https://example-documentation.com/
